version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-crmuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-crmpass}
      POSTGRES_DB: ${POSTGRES_DB:-crm}
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./
      dockerfile: ./crm-backend/Dockerfile
    container_name: crm-backend
    restart: always
    ports:
      - '3001:3000'
      - '5555:5555'
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-crmuser}:${POSTGRES_PASSWORD:-crmpass}@db:5432/${POSTGRES_DB:-crm}
      NODE_ENV: ${NODE_ENV:-staging}
      PORT: 3000
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./crm-backend:/app/crm-backend
      - ./shared:/app/shared
      - /app/crm-backend/node_modules
    working_dir: /app/crm-backend
    depends_on:
      - db
  
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    container_name: crm-frontend
    restart: always
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app/frontend
      - ./shared:/app/shared
      - /app/frontend/node_modules
    working_dir: /app/frontend
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:3000

volumes:
  db_data: